spring.application.name=Mltb
spring.datasource.url=jdbc:postgresql://localhost:5432/LearningTracker
spring.datasource.username=postgres
spring.datasource.password=root1234
spring.jpa.hibernate.ddl-auto=create-drop

# The first line logs the SQL queries, and the second statement logs the prepared statement parameters.
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE